// resources/assets/js/components/Vue/FeaturedPackages.vue
<template>

	<div class="col s12 m12">
		<h3 class="featured__package__title">Featured Packages</h3>
	</div>

	<div class="pattern pattern--hidden"></div>

	<featured-package
		v-for="package in packages" 
		:package = "package"
		>
	</featured-package>

</template>

<script>

	import FeaturedPackage from './FeaturedPackage.vue';

	export default {

		props: ['packages'],

		components: {

			FeaturedPackage

		}

	};

</script>

// resources/assets/js/components/React/FeaturedPackages.js
var React = require('react');
var ReactDOM = require('react-dom');

import FeaturedPackage from './FeaturedPackage';

var FeaturedPackages = React.createClass({

	componentDidMount() {
		console.log(window.packages);
	},
	
	render() {

		var featuredPackages = window.packages.map(function(currentPackage) {
			return (
				<FeaturedPackage key={currentPackage.id} currentPackage={currentPackage} />
				);
		});

		return (
			<div>
				<div className="col s12 m12">
					<h3 className="featured__package__title">Featured Packages</h3>
				</div>
				
				<div className="pattern pattern--hidden"></div>
				{ featuredPackages }
			</div>
		);
	}
});

ReactDOM.render(
	<FeaturedPackages />,
	document.getElementById('FeaturedPackages')
	);
