// resources/assets/js/components/Vue/FeaturedPackage.vue
<template>

	<div class="col s12 m4">
		<div class="card">
			<div class="card__container card__container--closed">
				<svg class="card__image" 
					xmlns="http://www.w3.org/2000/svg" 
					xmlns:xlink="http://www.w3.org/1999/xlink" 
					viewBox="0 0 1920 500" 
					preserveAspectRatio="xMidYMid slice"
				>
					<defs>
						<clipPath id="clipPath{{ package.id }}">
							<circle class="clip" cx="960" cy="250" r="992"></circle>
						</clipPath>
					</defs>
					<image clip-path="url(#clipPath{{ package.id }})" 
							width="1920" 
							height="650" 
							xlink:href="{{ imagePath }}"
					></image>
				</svg>
				<div class="card__content">

					<i class="card__btn-close fa fa-times"></i>
				
					<div class="card__caption">
						<h2 class="card__title">{{ package.name }}</h2>
						<p class="card__subtitle">{{ package.subtitle }}</p>
					</div>

					<div class="card__copy">
						<div class="col m12 s12">
							<div class="package">
								<div class="row">
									<div class="col m9 s12">
										{{{ package.description }}}
									</div>

									<div class="col m3 s12">
										<h3 class="package__price">
											{{ package.adult_price | currency currentCurrency }}
										</h3>

										<ul class="collection">
											<li class="collection-item">
												<strong>Departs:</strong> {{ package.departs }}
											</li>
											<li class="collection-item">
												<strong>Returns:</strong> {{ package.returns }}
											</li>								
											<li class="collection-item">
												<strong>Duration:</strong> {{ package.duration }}
											</li>
											<li class="collection-item">
												<strong>Adult:</strong> {{ package.adult_price }}
											</li>
											<li class="collection-item">
												<strong>Child:</strong> {{ package.child_price }}
											</li>

											<li class="collection-item" v-if="package.confirm_availability">
												Subject for Availability
											</li>								
										</ul>

										<a href="/package/{{ package.slug }}" class="btn btn-large btn-block waves-effect waves-light blue">View Package</a>

										<div class="share-package">
											
											<h6>Share this package</h6>

										</div>

									</div>
								</div>	
							</div>
						</div>		
					</div>
				</div>
			</div>
		</div>
	</div>

</template>

<script>


	export default {

		props: ['package'],

		ready() {

			

		},

		data() {

			return {

				uploadsPath: $('meta[name="uploads_path"]').attr('content'),

				currentCurrency: $('meta[name="current_currency"]').attr('content')

			}

		},

		computed: {


			imagePath() {

				return this.uploadsPath + this.package.photos[0].path;

			}

		}

	};

</script>

// resources/assets/js/components/React/FeaturedPackage.js
var React = require('react');

import PackagePrice from './PackagePrice';
import PackageInfo from './PackageInfo';

var FeaturedPackage = React.createClass({

	showSVG() {
		var clipPathId = 'clipPath' + this.props.currentPackage.id;
		var imagePath = '/images/uploads/' + this.props.currentPackage.photos[0].path;

		return {
			__html: `<svg class='card__image' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' viewBox='0 50 1920 500' preserveAspectRatio='xMidYMid slice'>
						<defs>
							<clipPath id=${clipPathId}>
								<circle class='clip' cx='960' cy='250' r='992'></circle>
							</clipPath>
						</defs>
						<image width='1920' height='650' clip-path='url(#clipPath${this.props.currentPackage.id})' xlink:href=${imagePath} />
					</svg>`
		}
	},

	showDescription() {
		return {
			__html: this.props.currentPackage.description
		}
	},

	render() {

		var packageUrl = '/package/' + this.props.currentPackage.slug;

		var svgStyle = {
			height: 'inherit'
		}

		return (
			<div className="col s12 m4">
				<div className="card">
					<div className="card__container card__container--closed">
						
						<div className="svg" dangerouslySetInnerHTML={this.showSVG()}></div>

						<div className="card__content">
							<i className="card__btn-close fa fa-times"></i>
							<div className="card__caption">
								<h2 className="card__title">{ this.props.currentPackage.name }</h2>
								<p className="card__subtitle">{ this.props.currentPackage.subtitle }</p>
							</div>

							<div className="card__copy">
								<div className="col m12 s12">
									<div className="package">
										<div className="row">
											<div className="col m9 s12">
												<p dangerouslySetInnerHTML={this.showDescription()}></p>
											</div>
											<div className="col m3 s12">
												<PackagePrice currentPackage={this.props.currentPackage} adultPrice={this.props.currentPackage.adult_price} />
												<PackageInfo currentPackage={this.props.currentPackage} adultPrice={this.props.currentPackage.adult_price} childPrice={this.props.currentPackage.child_price} />

												<a href={packageUrl} className="btn btn-large btn-block waves-effect waves-light blue">View Package</a>
											</div>
										</div>	
									</div>
								</div>		
							</div>
						</div>
					</div>
				</div>
			</div>
		);
	}
});

export default FeaturedPackage;
