// resources/assets/js/components/React/Package.js
var React = require('react');

var Package = React.createClass({
	render() {
		var packageUrl = '/package/' + this.props.currentPackage.slug;
		var imagePath = '/images/uploads/' + this.props.currentPackage.photos[0].path;

		return (
			<div className="col s12 m4 l4">
				<div className="card">
					<div className="card-image">
						<img src={imagePath} alt={this.props.currentPackage.name} title={this.props.currentPackage.name} className="img-responsive" />
					</div>

					<div className="card-action">
						<a href={packageUrl}>
							{this.props.currentPackage.name}
						</a>
					</div>
				</div>
			</div>
		);
	}
});

export default Package;

// resources/assets/js/components/Vue/Package.vue


<template>

	<div class="col m4 s12">
		<div class="card">
			<div class="card-image">
				<img v-bind="{src:imagePath}" alt="{{ package.name }}" title="{{ package.name }}" class="img-responsive" />
			</div>

			<div class="card-action">
				<a href="/package/{{ package.slug }}">{{ package.name }}</a>
			</div>
		</div>
	</div>


</template>


<script>

	export default {

		props: ['package'],

		data() {

			return {

				uploadsPath: $('meta[name="uploads_path"]').attr('content')

			}

		},

		computed: {

			imagePath() {

				return this.uploadsPath + this.package.photos[0].path;

			}

		}

	}

</script>
